doc(observer): add observer #INFR-1855
ngnice/ngnice.com pull request #8
Opened 2021-04-25 08:11 UTC by ggxxgxq

2021-04-26 00:22 UTC, why520crazy requested changes

2021-04-26 00:22 UTC, why520crazy commented on docs/rxjs/observer.md
> +什么是一个Observer? Observer是一个被Observable推送的值的消费者。Observers只是一系列回调，对应于Observable推送的next、error、complete三种类型的通知。下面的示例是一个经典的Observer的对象。
所有的英文单词前后加空格分割一下吧，和其他的文档保持一致。

2021-04-27 02:58 UTC, ggxxgxq commented on docs/rxjs/observer.md
> +什么是一个Observer? Observer是一个被Observable推送的值的消费者。Observers只是一系列回调，对应于Observable推送的next、error、complete三种类型的通知。下面的示例是一个经典的Observer的对象。
ok 已经加上了

2021-04-28 14:39 UTC, why520crazy approved these changes

2021-04-28 14:39 UTC, merged